### ISSUE TITLE
Iteration 1: User Interaction with Controlled Form

### ISSUE THREAD

**Issue by sdmisra** [sdmisra/birdWords#15]
As a user, I want to search for bird recordings.

 User actions: Enter a search query within form for bird recordings, hit enter or submit button.

   System actions: Retrieve and display the matching bird recordings based on the search query. 
  This will be a fetch request to our API, with the form value interpolated into the endpoint url according to the docs for our API.

**Comment by CBradsen** [comment]
When I pick categories from the search form and press submit I am taken to a new page that shows results that reflect what I chose to see. 

United States
dawn call
